### ISSUE TITLE
Coffes List

### ISSUE THREAD

**Issue by Sannsfilm** [Sannsfilm/code-review-challenge#2]
## Value Proposition

**As a user**

**I want to** browse a list of recipes,

**so that** I can discover my favorite recipes.

## Description

![Image](https://github.com/user-attachments/assets/59a8769d-1e30-4ceb-be78-b82bd58c0e45)

## Acceptance Criteria

- The homepage displays a list of coffees.
- Each coffee listing includes:
  - Coffee title
  - Coffee image
  - Descriptions or features of the coffee
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/coffees-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/coffees.json)
- [ ] Add an `imageUrl` for each coffee, for example from [unsplash.com](https://unsplash.com)
- [ ] Coffees List is displayed on the Home page
- [ ] The coffee image is displayed
- [ ] The coffee title is displayed
- [ ] The descriptions or features are displayed
